In [29]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('Dataset2.csv').values

In [30]:
np.any(np.isnan(dataset))

True

In [31]:
np.all(np.isfinite(dataset))

False

In [32]:
col_mean = np.nanmean(dataset, axis = 0)


In [33]:
inds = np.where(np.isnan(dataset))


In [34]:
dataset[inds] = np.take(col_mean, inds[1])

In [35]:
indi=np.where(np.isnan(dataset))
indi

(array([], dtype=int64), array([], dtype=int64))

In [36]:
data=dataset[:,0:12]
target=dataset[:,13]

target=np.reshape(target, (-1,1))

print(data[:3])
print(target[:3])

[[53.5         2.          1.         29.11120713  0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [65.4         2.          1.         29.11120713  0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [83.          1.          2.         29.46        1.          1.
   0.          0.          0.          0.          0.          0.        ]]
[[6.45]
 [6.48]
 [6.67]]


In [37]:
data[:,3][26]

24.24

In [38]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [39]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [40]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print("r2 score:",r2) 

r2 score: 0.01545720820420493


In [42]:
test1=[[29.3,   2,    2,   21.84,  0,    0,    0,    0,    0,    0,    0,    0  ]]

In [43]:
test2=[[68.4,   2,    1,   20.9,   0,    0,    0,    0,    0,    1,   0,    0  ]]

In [44]:
#0.10

In [28]:
import pickle
pickle.dump(model, open('hipLRwC.pkl', 'wb'))

In [45]:
model.predict(test1)

array([[7.90458972]])

In [46]:
model.predict(test2)

array([[7.8653774]])

In [41]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(test_target, predicted_target)

0.31080622574869465